#!/usr/bin/env bash
# Commands instals Nginx on Web-Sever-01

# Updatwa Packages before  Installations
sudo apt-get update
sudo apt-get -y install nginx

# Configurese Uncomplicated Firewall (UFW) to permit incoming to real traffic for the  Nginx HTTP service
sudo ufw allow 'Nginx HTTP'

# Creating an index.html page
echo "Hello World!" | sudo tee /var/www/html/index.html

# Tests Nginx configurations for Syntax errors
sudo nginx -t

# Restarting Nginx
sudo service nginx start
