#!/usr/bin/env bash
# Th script will list ll numbers from 1 to 100
# Will display FizzBuzz when its multiple of 3 and 5
# will show Fizz when the no is multiple of 3
#will show Buzz when number is a multiple of 5
# Otherwise, show the number
# In a list format
i="1"
while [ $i -le 100 ]; do
    if [ $((i % 3)) == 0 ] && [ $((i % 5)) == 0 ]
    then
        echo "FizzBuzz"
    elif [ $((i % 3)) == 0 ]
    then
        echo "Fizz"
    elif [ $((i % 5)) == 0 ]
    then
        echo "Buzz"
    else
        echo "$i"
    fi
    (( i++ ))
done
