#!/usr/bin/env bash
# The script will display the file contentfile /etc/passwd
# Format: The user USERNAME GROUP_ID gang, 
# lives in HOME_DIRECTORY and COMMAND/SHELL. USER ID's 
# place passcode PASSWORD, info about the user: USER ID INFO
while IFS=: read -r f1 f2 f3 f4 f5 f6 f7
do 
 echo "The user $f1 is part of the $f4 gang, lives in $f6 and rides $f7. $f3's place is protected by the passcode $f2, more info about the user here: $f5"
done < /etc/passwd
