#!/usr/bin/env bash
# The script will display "Best School" 10 times 
# except 9th iteration, displays Best School and then Hi
i="1"
while [ $i -le 10 ]; do
    echo "Best School"
    if [ $i -eq 9 ]
    then
        echo "Hi"
    fi
    (( i++ ))
    done
